version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/ylck/local_ip_ddns

    steps:
      - checkout

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: go get -t -d -v ./...
      - run: go build -v